### ISSUE TITLE
Hypersweeper does not provide config_id

### ISSUE THREAD

**Issue by LukasFehring** [automl/hypersweeper#12]
* HyperSweeper version: Any
* Python version: Any
* Operating System: Any

#### Description

When executing Hyperband using SMAC, each config has a consistent `config_id` attribute. The serialized configuration used by the hypersweeper does not seem to provide that configid. To start execution based on the lower fidelity results, this should probably be adapted, to provide an easy way of continuing execution.

#### Steps/Code to Reproduce

Located at /hydra_plugins/hypersweeper/hypersweeper_sweeper.py we can see that the configuration_id is disregarded
```
info, terminate = self.optimizer.ask()
configs.append(info.config)
```

**Comment by TheEimer** [comment]
This is not trivial since this kind of information is pretty unique to SMAC... but if SMAC just counts up, it matches the hypersweeper one anyway and as far as I can see that's the case. I'm not including these since I'm not creating a different log loop just for this one SMAC value. SMAC logs everything on its own anyway, I don't see the big benefit of so much code overhead.
